FROM python:3

ENV PYTHONUNBUFFERED=0

WORKDIR /usr/src/app

RUN apt-get -q update && apt-get -qy install netcat

COPY ./requirements/requirement-dev.txt /usr/src/app
RUN pip install -r requirement-dev.txt